import { Product } from "@/store/useCartStore";

export interface Category {
  id: string;
  name: string;
  icon: string;
  count: number;
  subcategories: string[];
}

export const CATEGORIES: Category[] = [
  {
    id: "all",
    name: "All Products",
    icon: "🛍️",
    count: 24,
    subcategories: ["All Items"],
  },
  {
    id: "grocery_kitchen",
    name: "Grocery & Kitchen",
    icon: "🥬",
    count: 12,
    subcategories: [
      "All Items",
      "Vegetables & Fruits",
      "Atta, Rice & Dal",
      "Oil, Ghee & Masala",
      "Dairy, Bread & Eggs",
      "Dry Fruits & Cereals",
      "Chicken, Meat & Fish",
      "Kitchenware & Appliances",
    ],
  },
  {
    id: "snacks_drinks",
    name: "Snacks & Drinks",
    icon: "🍿",
    count: 9,
    subcategories: [
      "All Items",
      "Bakery & Biscuits",
      "Chips & Namkeen",
      "Sweets & Chocolates",
      "Drinks & Juices",
      "Tea, Coffee & Milk Drinks",
      "Instant Food",
      "Sauces & Spreads",
      "Ice Creams & More",
      "Paan Corner",
    ],
  },
  {
    id: "beauty_personal_care",
    name: "Beauty & Personal Care",
    icon: "✨",
    count: 8,
    subcategories: [
      "All Items",
      "Bath & Body",
      "Hair Care",
      "Skin & Face Care",
      "Beauty & Cosmetics",
      "Feminine Hygiene",
      "Baby Care",
      "Health & Pharma",
      "Sexual Wellness",
    ],
  },
  {
    id: "home_electronics",
    name: "Home, Electronics & Others",
    icon: "🏠",
    count: 5,
    subcategories: [
      "All Items",
      "Home & Lifestyle",
      "Cleaners & Repellents",
      "Electronics & Appliances",
      "Stationery & Games",
      "Pet Care",
    ],
  },
  {
    id: "lit_specialty",
    name: "LIT (Specialty)",
    icon: "🔥",
    count: 4,
    subcategories: [
      "All Items",
      "Tobacco & Smoking Essentials",
      "Hookah & Accessories",
      "Adult & Novelty Products",
      "Specialty Cosmetics",
    ],
  },
];

export interface ExtendedProduct extends Product {
  sku?: string;
  costPrice?: number;
  subcategory?: string;
  description?: string;
  nutritionalInfo?: {
    calories: string;
    protein: string;
    carbs: string;
    fat: string;
  };
  tags?: string[];
  inStock?: boolean;
}

export const PRODUCTS: ExtendedProduct[] = [
  {
    id: "p1",
    name: "Organic Farm Fresh Tomatoes",
    price: 38,
    originalPrice: 50,
    category: "grocery_kitchen",
    subcategory: "Vegetables & Fruits",
    weight: "500 g",
    rating: 4.8,
    deliveryTime: "8 mins",
    stock: 45,
    inStock: true,
    description: "Hand-picked organic farm-fresh red tomatoes. Rich in Lycopene, Vitamin C, and essential antioxidants.",
    nutritionalInfo: { calories: "18 kcal / 100g", protein: "0.9 g", carbs: "3.9 g", fat: "0.2 g" },
    tags: ["tomato", "organic", "vegetable", "fresh"],
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p2",
    name: "Fresh Hybrid Capsicum Green",
    price: 42,
    originalPrice: 55,
    category: "grocery_kitchen",
    subcategory: "Vegetables & Fruits",
    weight: "250 g",
    rating: 4.7,
    deliveryTime: "10 mins",
    stock: 18,
    inStock: true,
    description: "Crispy green bell peppers harvested fresh. Perfect for stir-fries, salads, and pizza toppings.",
    nutritionalInfo: { calories: "20 kcal / 100g", protein: "0.9 g", carbs: "4.6 g", fat: "0.2 g" },
    tags: ["capsicum", "pepper", "green", "vegetable"],
    imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p3",
    name: "Fresh Red Onion (Pyaz)",
    price: 29,
    originalPrice: 35,
    category: "grocery_kitchen",
    subcategory: "Vegetables & Fruits",
    weight: "1 kg",
    rating: 4.9,
    deliveryTime: "7 mins",
    stock: 120,
    inStock: true,
    description: "Premium quality red onions sourced directly from Maharashtra farms. Firm, pungent, and long-lasting.",
    nutritionalInfo: { calories: "40 kcal / 100g", protein: "1.1 g", carbs: "9.3 g", fat: "0.1 g" },
    tags: ["onion", "pyaz", "vegetable", "staple"],
    imageUrl: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p4",
    name: "Aashirvaad Shuddh Chakki Atta",
    price: 245,
    originalPrice: 280,
    category: "grocery_kitchen",
    subcategory: "Atta, Rice & Dal",
    weight: "5 kg",
    rating: 4.9,
    deliveryTime: "10 mins",
    stock: 60,
    inStock: true,
    description: "100% pure whole wheat flour milled from high quality golden grains.",
    nutritionalInfo: { calories: "340 kcal / 100g", protein: "11.0 g", carbs: "72.0 g", fat: "1.8 g" },
    tags: ["atta", "flour", "wheat", "grocery"],
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p5",
    name: "Fortune Sunlite Refined Sunflower Oil",
    price: 135,
    originalPrice: 160,
    category: "grocery_kitchen",
    subcategory: "Oil, Ghee & Masala",
    weight: "1 L Pouch",
    rating: 4.8,
    deliveryTime: "8 mins",
    stock: 40,
    inStock: true,
    description: "Light, healthy refined sunflower oil enriched with Vitamins A & D.",
    nutritionalInfo: { calories: "900 kcal / 100g", protein: "0 g", carbs: "0 g", fat: "100 g" },
    tags: ["oil", "sunflower", "cooking", "grocery"],
    imageUrl: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p6",
    name: "Amul Taaza Toned Milk",
    price: 28,
    originalPrice: 30,
    category: "grocery_kitchen",
    subcategory: "Dairy, Bread & Eggs",
    weight: "500 ml",
    rating: 4.9,
    deliveryTime: "5 mins",
    stock: 85,
    inStock: true,
    description: "Pasteurised toned milk with 3.0% fat and 8.5% SNF. Hygienically processed.",
    nutritionalInfo: { calories: "58 kcal / 100ml", protein: "3.1 g", carbs: "4.7 g", fat: "3.0 g" },
    tags: ["milk", "amul", "dairy", "drink"],
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p7",
    name: "Britannia 100% Whole Wheat Bread",
    price: 45,
    originalPrice: 50,
    category: "grocery_kitchen",
    subcategory: "Dairy, Bread & Eggs",
    weight: "400 g",
    rating: 4.8,
    deliveryTime: "6 mins",
    stock: 35,
    inStock: true,
    description: "Healthy 100% whole wheat bread baked with natural wheat fiber.",
    nutritionalInfo: { calories: "245 kcal / 100g", protein: "8.5 g", carbs: "47.0 g", fat: "2.1 g" },
    tags: ["bread", "wheat", "bakery"],
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p8",
    name: "Lay's India's Magic Masala Potato Chips",
    price: 20,
    originalPrice: 20,
    category: "snacks_drinks",
    subcategory: "Chips & Namkeen",
    weight: "50 g",
    rating: 4.9,
    deliveryTime: "5 mins",
    stock: 150,
    inStock: true,
    description: "Crispy potato chips spiced with iconic Indian Magic Masala blend.",
    nutritionalInfo: { calories: "540 kcal / 100g", protein: "7.0 g", carbs: "53.0 g", fat: "33.0 g" },
    tags: ["lays", "chips", "namkeen", "snack"],
    imageUrl: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p9",
    name: "Coca-Cola Zero Sugar",
    price: 40,
    originalPrice: 45,
    category: "snacks_drinks",
    subcategory: "Drinks & Juices",
    weight: "300 ml Can",
    rating: 4.7,
    deliveryTime: "5 mins",
    stock: 64,
    inStock: true,
    description: "Crisp, refreshing Coca-Cola flavor with Zero Sugar and Zero Calories.",
    nutritionalInfo: { calories: "0 kcal", protein: "0 g", carbs: "0 g", fat: "0 g" },
    tags: ["coke", "coca-cola", "drink", "soda"],
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p10",
    name: "Maggi 2-Minute Masala Noodles",
    price: 14,
    originalPrice: 15,
    category: "snacks_drinks",
    subcategory: "Instant Food",
    weight: "70 g Pack",
    rating: 4.9,
    deliveryTime: "6 mins",
    stock: 200,
    inStock: true,
    description: "India's favorite instant noodles infused with signature 12-spice masala tastemaker.",
    nutritionalInfo: { calories: "420 kcal / 100g", protein: "8.0 g", carbs: "63.0 g", fat: "15.0 g" },
    tags: ["maggi", "instant", "noodles", "snack"],
    imageUrl: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p11",
    name: "Nivea Body Milk Nourishing Body Lotion",
    price: 299,
    originalPrice: 350,
    category: "beauty_personal_care",
    subcategory: "Bath & Body",
    weight: "400 ml",
    rating: 4.8,
    deliveryTime: "8 mins",
    stock: 25,
    inStock: true,
    description: "Deep moisture body lotion enriched with almond oil for 48h dry skin relief.",
    tags: ["nivea", "lotion", "skin", "beauty"],
    imageUrl: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=80",
  },
  {
    id: "p12",
    name: "Colin Glass & Surface Cleaner Spray",
    price: 105,
    originalPrice: 120,
    category: "home_electronics",
    subcategory: "Cleaners & Repellents",
    weight: "500 ml",
    rating: 4.7,
    deliveryTime: "9 mins",
    stock: 30,
    inStock: true,
    description: "Shine boost formula for streak-free glass, mirror, and appliance cleaning.",
    tags: ["colin", "cleaner", "home"],
    imageUrl: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=500&auto=format&fit=crop&q=80",
  },
];
